# Generated by Django 4.2.6 on 2023-10-30 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_funcionario_cargo_funcionario_setor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setor',
            old_name='setor',
            new_name='descricao',
        ),
    ]
