# Generated by Django 4.2.6 on 2023-10-30 19:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_setor_setor_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='data_abertura',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
